Added central configuration script.

diff --git a/applications/rendering/toposm/import_nhd b/applications/rendering/toposm/import_nhd
--- a/applications/rendering/toposm/import_nhd
+++ b/applications/rendering/toposm/import_nhd
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 
-# unpacked NHD shapefiles in the following directory:
-SRCDIR="temp/nhd"
-
-DATABASE="gis"
+if [[ -z $TOPOSM_ENV_SET ]]; then
+    echo "Error: TopOSM environment not set."
+    exit 1
+fi
 
 # HACK: Removes transaction support for shp2pgsql
 # because a few lines in each file contain illegal characters, aborting
@@ -11,79 +11,75 @@ DATABASE="gis"
 # but that's for later...
 FILTER='s/BEGIN;//g'
 
+DBCMD="psql -q -p $DB_PORT $DB_NAME $DB_USER"
+
 # NOTE: The data type for fcode and ftype is changed because, for some
 # reason, mapnik (silently) fails to filter on bigint columns.
 
 # areas
 PREP_TABLE=1
-for SRCFILE in $SRCDIR/nhdarhi*.shp; do
-#for SRCFILE in $SRCDIR/processed/area*.shp; do
+for SRCFILE in $NHD_DIR/nhdarhi*.shp; do
     if [ "$PREP_TABLE" ]; then 
-	echo "Creating nhdarea table..."
-	shp2pgsql -p -I -g way "$SRCFILE" nhdarea | psql -q $DATABASE
-	shp2pgsql -p -I -g way "$SRCFILE" nhdarea_major | psql -q $DATABASE
+	    echo "Creating ${NHD_TABLE_PREFIX}_area table..."
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_area | $DBCMD
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_area_major | $DBCMD
     fi
     echo "Importing $SRCFILE..."
-    shp2pgsql -a -g way "$SRCFILE" nhdarea | psql -q $DATABASE
+    shp2pgsql -a -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_area | \
+        sed "$FILTER" | $DBCMD
     unset PREP_TABLE
 done
-echo "ALTER TABLE nhdarea ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | psql -q $DATABASE
-echo "ALTER TABLE nhdarea_major ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | psql -q $DATABASE
-
+echo "ALTER TABLE ${NHD_TABLE_PREFIX}_area ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
+echo "ALTER TABLE ${NHD_TABLE_PREFIX}_area_major ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
 echo "Extracting major areas..."
-echo "INSERT INTO nhdarea_major SELECT * FROM nhdarea WHERE areasqkm > 1" | psql -q $DATABASE
+echo "INSERT INTO ${NHD_TABLE_PREFIX}_area_major SELECT * FROM ${NHD_TABLE_PREFIX}_area WHERE areasqkm > 1" | $DBCMD
 
 # flowlines
 PREP_TABLE=1
-for SRCFILE in $SRCDIR/nhdflh??.shp; do
+for SRCFILE in $NHD_DIR/nhdflh??.shp; do
     if [ "$PREP_TABLE" ]; then 
-	echo "Creating nhdflowline table..."
-	shp2pgsql -p -I -g way "$SRCFILE" nhdflowline | psql -q $DATABASE
-	shp2pgsql -p -I -g way "$SRCFILE" nhdflowline_major | psql -q $DATABASE
+	    echo "Creating ${NHD_TABLE_PREFIX}_flowline table..."
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline | $DBCMD
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline_major | $DBCMD
     fi
     echo "Importing $SRCFILE..."
-    shp2pgsql -a -g way "$SRCFILE" nhdflowline | \
-	sed "$FILTER" | \
-	psql -q $DATABASE
+    shp2pgsql -a -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_flowline | \
+	    sed "$FILTER" | $DBCMD
     unset PREP_TABLE
 done
-echo "ALTER TABLE nhflowline ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | psql -q $DATABASE
-
+echo "ALTER TABLE ${NHD_TABLE_PREFIX}_flowline ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
 echo "Extracting major flowlines..."
-echo "INSERT INTO nhdflowline_major SELECT * FROM nhdflowline WHERE lengthkm > 2" | psql -q $DATABASE
+echo "INSERT INTO ${NHD_TABLE_PREFIX}_flowline_major SELECT * FROM ${NHD_TABLE_PREFIX}_flowline WHERE lengthkm > 2" | $DBCMD
 
 # points
 PREP_TABLE=1
-for SRCFILE in $SRCDIR/nhdpthi*.shp; do
+for SRCFILE in $NHD_DIR/nhdpthi*.shp; do
     if [ "$PREP_TABLE" ]; then 
-	echo "Creating nhdpoint table..."
-	shp2pgsql -p -I -g way "$SRCFILE" nhdpoint | psql -q $DATABASE
+	    echo "Creating ${NHD_TABLE_PREFIX}_point table..."
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_point | $DBCMD
     fi
     echo "Importing $SRCFILE..."
-    shp2pgsql -a -g way "$SRCFILE" nhdpoint | \
-	sed "$FILTER" | \
-	psql -q $DATABASE
+    shp2pgsql -a -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_point | \
+	    sed "$FILTER" | $DBCMD
     unset PREP_TABLE
 done
-echo "ALTER TABLE nhdpoint ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | psql -q $DATABASE
+echo "ALTER TABLE ${NHD_TABLE_PREFIX}_point ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
 
 # waterbodies
 PREP_TABLE=1
-for SRCFILE in $SRCDIR/nhdwbhi*.shp; do
+for SRCFILE in $NHD_DIR/nhdwbhi*.shp; do
     if [ "$PREP_TABLE" ]; then 
-	echo "Creating nhdwaterbody table..."
-	shp2pgsql -p -I -g way "$SRCFILE" nhdwaterbody | psql -q $DATABASE
-	shp2pgsql -p -I -g way "$SRCFILE" nhdwaterbody_major | psql -q $DATABASE
+	    echo "Creating ${NHD_TABLE_PREFIX}_waterbody table..."
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody | $DBCMD
+	    shp2pgsql -p -I -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody_major | $DBCMD
     fi
     echo "Importing $SRCFILE..."
-    shp2pgsql -a -g way "$SRCFILE" nhdwaterbody | \
-	sed "$FILTER" | \
-	psql -q $DATABASE
+    shp2pgsql -a -g way "$SRCFILE" ${NHD_TABLE_PREFIX}_waterbody | \
+	    sed "$FILTER" | $DBCMD
     unset PREP_TABLE
 done
-echo "ALTER TABLE nhdwaterbody ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | psql -q $DATABASE
-
+echo "ALTER TABLE ${NHD_TABLE_PREFIX}_waterbody ALTER COLUMN fcode TYPE INT, ALTER COLUMN ftype TYPE INT" | $DBCMD
 echo "Extracting major waterbodies..."
-echo "INSERT INTO nhdwaterbody_major SELECT * FROM nhdwaterbody WHERE areasqkm > 1" | psql -q $DATABASE
+echo "INSERT INTO ${NHD_TABLE_PREFIX}_waterbody_major SELECT * FROM ${NHD_TABLE_PREFIX}_waterbody WHERE areasqkm > 1" | $DBCMD
 
 echo "Done."
diff --git a/applications/rendering/toposm/import_planet b/applications/rendering/toposm/import_planet
--- a/applications/rendering/toposm/import_planet
+++ b/applications/rendering/toposm/import_planet
@@ -1,22 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
 # Imports one or more planet dumps (*.osm.bz2, *.osm) or
 # planet diffs (*.osc.gz, *.osc).
 
-DATABASE="osmdb"
-PORT="5432"
-STYLEFILE="default.style"
-PREFIX="us_osm"
-DBCMD="psql -q $DATABASE"
-BBOX="-127,23,-65,51" # limit to continental US
+if [[ -z $TOPOSM_ENV_SET ]]; then
+    echo "Error: TopOSM environment not set."
+    exit 1
+fi
 
 if [ -z "$1" ]; then
     echo "Syntax: import_planet <file> [<file> ...]"
+    exit 2
 fi
 
 
-# Import data files.
+DBCMD="psql -q -p $DB_PORT $DB_NAME $DB_USER"
 
+# Import data files.
 while [ $# -gt 0 ]; do
     SRCFILE="$1"
     
@@ -50,20 +50,18 @@ while [ $# -gt 0 ]; do
     # Import the file.
 	$CAT "$SRCFILE" | \
         sed "s/v=\"coastline\"/v=\"cXline\"/g" | \
-        osm2pgsql -m $OPERATOR --bbox "$BBOX" \
-          --style "$STYLEFILE" -P $PORT -d "$DATABASE" \
-          --prefix "$PREFIX" \
+        osm2pgsql -m $OPERATOR --bbox "$EXTENTS_LATLON" \
+          --style "$OSM2PGSQL_STYLE_FILE" -P $DB_PORT -d "$DB_NAME" \
+          -U "$DB_USER" --prefix "$DB_PREFIX" \
           --slim -C 2000 -	
 
 	shift
 done
 
-
 # Rename coastline tags back.
-
 for SUFFIX in line point polygon roads; do
-    echo "Renaming coastlines in ${PREFIX}_${SUFFIX}..."
-    echo "UPDATE ${PREFIX}_${SUFFIX} SET \"natural\"='coastline' WHERE \"natural\"='cXline'" | $DBCMD
+    echo "Renaming coastlines in ${DB_PREFIX}_${SUFFIX}..."
+    echo "UPDATE ${DB_PREFIX}_${SUFFIX} SET \"natural\"='coastline' WHERE \"natural\"='cXline'" | $DBCMD
 done
 
 
@@ -72,15 +70,15 @@ done
 # TODO: This fails if column exists. Not a problem, but should be
 # handled more gracefully.
 echo "Adding road numbers column..."
-echo "ALTER TABLE ${PREFIX}_roads ADD COLUMN roadnumber VARCHAR(10);" | $DBCMD
+echo "ALTER TABLE ${DB_PREFIX}_roads ADD COLUMN roadnumber VARCHAR(10);" | $DBCMD
 
 # interstates
-echo "UPDATE ${PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'I[ -]([0-9]+)') WHERE (highway = 'motorway' OR highway = 'trunk') AND (ref LIKE 'I %' OR ref LIKE 'I-%')" | $DBCMD
+echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'I[ -]([0-9]+)') WHERE (highway = 'motorway' OR highway = 'trunk') AND (ref LIKE 'I %' OR ref LIKE 'I-%')" | $DBCMD
 # US routes
-echo "UPDATE ${PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'US ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'US %'" | $DBCMD
+echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'US ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'US %'" | $DBCMD
 # state routes
-echo "UPDATE ${PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'SR ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'SR %'" | $DBCMD
-echo "UPDATE ${PREFIX}_roads SET roadnumber = SUBSTRING(name FROM 'State Highway ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND name LIKE 'State Highway %'" | $DBCMD
+echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'SR ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'SR %'" | $DBCMD
+echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(name FROM 'State Highway ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND name LIKE 'State Highway %'" | $DBCMD
 # CO routes
-echo "UPDATE ${PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'C ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'C %'" | $DBCMD
+echo "UPDATE ${DB_PREFIX}_roads SET roadnumber = SUBSTRING(ref FROM 'C ([0-9A-Z]+)') WHERE (highway <> '' AND highway IS NOT NULL) AND ref LIKE 'C %'" | $DBCMD
 
diff --git a/applications/rendering/toposm/prep_contours_table b/applications/rendering/toposm/prep_contours_table
--- a/applications/rendering/toposm/prep_contours_table
+++ b/applications/rendering/toposm/prep_contours_table
@@ -1,4 +1,12 @@
-#!/bin/sh
-shp2pgsql -p -I -g way contours.shp contours_us_50ft | psql -q gis
-echo "ALTER TABLE contours_us_50ft ADD COLUMN height_ft INT" | psql -q gis
+#!/bin/bash
+
+if [[ -z $TOPOSM_ENV_SET ]]; then
+    echo "Error: TopOSM environment not set."
+    exit 1
+fi
+
+DBCMD="psql -q -p $DB_PORT $DB_NAME $DB_USER"
+
+shp2pgsql -p -I -g way contours.shp $CONTOURS_TABLE | $DBCMD
+echo "ALTER TABLE $CONTOURS_TABLE ADD COLUMN height_ft INT" | $DBCMD
 
